<?xml version="1.0" encoding="utf-8"?>
<testsuites><testsuite name="django.contrib.contenttypes.tests.ContentTypesTests"><testcase classname="django.contrib.contenttypes.tests.ContentTypesTests" name="test_get_for_concrete_model" time="0.518272"></testcase><testcase classname="django.contrib.contenttypes.tests.ContentTypesTests" name="test_get_for_concrete_models" time="0.513903"></testcase><testcase classname="django.contrib.contenttypes.tests.ContentTypesTests" name="test_get_for_models_empty_cache" time="0.172378"></testcase><testcase classname="django.contrib.contenttypes.tests.ContentTypesTests" name="test_get_for_models_full_cache" time="0.256905"></testcase><testcase classname="django.contrib.contenttypes.tests.ContentTypesTests" name="test_get_for_models_partial_cache" time="0.257010"></testcase><testcase classname="django.contrib.contenttypes.tests.ContentTypesTests" name="test_lookup_cache" time="0.344450"></testcase><testcase classname="django.contrib.contenttypes.tests.ContentTypesTests" name="test_missing_model" time="0.254331"></testcase><testcase classname="django.contrib.contenttypes.tests.ContentTypesTests" name="test_shortcut_view" time="0.518047"></testcase><testcase classname="django.contrib.contenttypes.tests.ContentTypesTests" name="test_shortcut_view_with_broken_get_absolute_url" time="0.512235"></testcase><testcase classname="django.contrib.contenttypes.tests.ContentTypesTests" name="test_shortcut_view_without_get_absolute_url" time="0.427078"></testcase></testsuite><testsuite name="django.contrib.sessions.tests.CacheDBSessionTests"><testcase classname="django.contrib.sessions.tests.CacheDBSessionTests" name="test_actual_expiry" time="1.346201"></testcase><testcase classname="django.contrib.sessions.tests.CacheDBSessionTests" name="test_clear" time="0.000543"></testcase><testcase classname="django.contrib.sessions.tests.CacheDBSessionTests" name="test_custom_expiry_datetime" time="0.000596"></testcase><testcase classname="django.contrib.sessions.tests.CacheDBSessionTests" name="test_custom_expiry_reset" time="0.000584"></testcase><testcase classname="django.contrib.sessions.tests.CacheDBSessionTests" name="test_custom_expiry_seconds" time="0.000586"></testcase><testcase classname="django.contrib.sessions.tests.CacheDBSessionTests" name="test_custom_expiry_timedelta" time="0.000598"></testcase><testcase classname="django.contrib.sessions.tests.CacheDBSessionTests" name="test_cycle" time="1.180187"></testcase><testcase classname="django.contrib.sessions.tests.CacheDBSessionTests" name="test_decode" time="0.001409"></testcase><testcase classname="django.contrib.sessions.tests.CacheDBSessionTests" name="test_decode_failure_logged_to_security" time="0.000957"></testcase><testcase classname="django.contrib.sessions.tests.CacheDBSessionTests" name="test_default_expiry" time="0.000667"></testcase><testcase classname="django.contrib.sessions.tests.CacheDBSessionTests" name="test_delete" time="1.281550"></testcase><testcase classname="django.contrib.sessions.tests.CacheDBSessionTests" name="test_exists_searches_cache_first" time="1.096303"></testcase><testcase classname="django.contrib.sessions.tests.CacheDBSessionTests" name="test_flush" time="1.275317"></testcase><testcase classname="django.contrib.sessions.tests.CacheDBSessionTests" name="test_get_empty" time="0.000476"></testcase><testcase classname="django.contrib.sessions.tests.CacheDBSessionTests" name="test_get_expire_at_browser_close" time="0.001417"></testcase><testcase classname="django.contrib.sessions.tests.CacheDBSessionTests" name="test_has_key" time="0.000493"></testcase><testcase classname="django.contrib.sessions.tests.CacheDBSessionTests" name="test_invalid_key" time="1.187970"></testcase><testcase classname="django.contrib.sessions.tests.CacheDBSessionTests" name="test_iteritems" time="0.000271"></testcase><testcase classname="django.contrib.sessions.tests.CacheDBSessionTests" name="test_iterkeys" time="0.000685"></testcase><testcase classname="django.contrib.sessions.tests.CacheDBSessionTests" name="test_itervalues" time="0.000261"></testcase><testcase classname="django.contrib.sessions.tests.CacheDBSessionTests" name="test_load_overlong_key" time="0.683980"></testcase><testcase classname="django.contrib.sessions.tests.CacheDBSessionTests" name="test_new_session" time="0.000404"></testcase><testcase classname="django.contrib.sessions.tests.CacheDBSessionTests" name="test_pop" time="0.000528"></testcase><testcase classname="django.contrib.sessions.tests.CacheDBSessionTests" name="test_pop_default" time="0.000516"></testcase><testcase classname="django.contrib.sessions.tests.CacheDBSessionTests" name="test_save" time="1.110992"></testcase><testcase classname="django.contrib.sessions.tests.CacheDBSessionTests" name="test_session_key_is_read_only" time="0.170235"></testcase><testcase classname="django.contrib.sessions.tests.CacheDBSessionTests" name="test_setdefault" time="0.000539"></testcase><testcase classname="django.contrib.sessions.tests.CacheDBSessionTests" name="test_store" time="0.000497"></testcase><testcase classname="django.contrib.sessions.tests.CacheDBSessionTests" name="test_update" time="0.000496"></testcase><testcase classname="django.contrib.sessions.tests.CacheDBSessionTests" name="test_values" time="0.000587"></testcase></testsuite><testsuite name="django.contrib.sessions.tests.CacheDBSessionWithTimeZoneTests"><testcase classname="django.contrib.sessions.tests.CacheDBSessionWithTimeZoneTests" name="test_actual_expiry" time="1.265730"></testcase><testcase classname="django.contrib.sessions.tests.CacheDBSessionWithTimeZoneTests" name="test_clear" time="0.000601"></testcase><testcase classname="django.contrib.sessions.tests.CacheDBSessionWithTimeZoneTests" name="test_custom_expiry_datetime" time="0.000698"></testcase><testcase classname="django.contrib.sessions.tests.CacheDBSessionWithTimeZoneTests" name="test_custom_expiry_reset" time="0.000731"></testcase><testcase classname="django.contrib.sessions.tests.CacheDBSessionWithTimeZoneTests" name="test_custom_expiry_seconds" time="0.000657"></testcase><testcase classname="django.contrib.sessions.tests.CacheDBSessionWithTimeZoneTests" name="test_custom_expiry_timedelta" time="0.000710"></testcase><testcase classname="django.contrib.sessions.tests.CacheDBSessionWithTimeZoneTests" name="test_cycle" time="1.186168"></testcase><testcase classname="django.contrib.sessions.tests.CacheDBSessionWithTimeZoneTests" name="test_decode" time="0.001142"></testcase><testcase classname="django.contrib.sessions.tests.CacheDBSessionWithTimeZoneTests" name="test_decode_failure_logged_to_security" time="0.000941"></testcase><testcase classname="django.contrib.sessions.tests.CacheDBSessionWithTimeZoneTests" name="test_default_expiry" time="0.000675"></testcase><testcase classname="django.contrib.sessions.tests.CacheDBSessionWithTimeZoneTests" name="test_delete" time="1.264334"></testcase><testcase classname="django.contrib.sessions.tests.CacheDBSessionWithTimeZoneTests" name="test_exists_searches_cache_first" time="1.096795"></testcase><testcase classname="django.contrib.sessions.tests.CacheDBSessionWithTimeZoneTests" name="test_flush" time="1.260140"></testcase><testcase classname="django.contrib.sessions.tests.CacheDBSessionWithTimeZoneTests" name="test_get_empty" time="0.000493"></testcase><testcase classname="django.contrib.sessions.tests.CacheDBSessionWithTimeZoneTests" name="test_get_expire_at_browser_close" time="0.001508"></testcase><testcase classname="django.contrib.sessions.tests.CacheDBSessionWithTimeZoneTests" name="test_has_key" time="0.000537"></testcase><testcase classname="django.contrib.sessions.tests.CacheDBSessionWithTimeZoneTests" name="test_invalid_key" time="1.188369"></testcase><testcase classname="django.contrib.sessions.tests.CacheDBSessionWithTimeZoneTests" name="test_iteritems" time="0.000567"></testcase><testcase classname="django.contrib.sessions.tests.CacheDBSessionWithTimeZoneTests" name="test_iterkeys" time="0.000560"></testcase><testcase classname="django.contrib.sessions.tests.CacheDBSessionWithTimeZoneTests" name="test_itervalues" time="0.000585"></testcase><testcase classname="django.contrib.sessions.tests.CacheDBSessionWithTimeZoneTests" name="test_load_overlong_key" time="0.690708"></testcase><testcase classname="django.contrib.sessions.tests.CacheDBSessionWithTimeZoneTests" name="test_new_session" time="0.000141"></testcase><testcase classname="django.contrib.sessions.tests.CacheDBSessionWithTimeZoneTests" name="test_pop" time="0.000531"></testcase><testcase classname="django.contrib.sessions.tests.CacheDBSessionWithTimeZoneTests" name="test_pop_default" time="0.000527"></testcase><testcase classname="django.contrib.sessions.tests.CacheDBSessionWithTimeZoneTests" name="test_save" time="1.098394"></testcase><testcase classname="django.contrib.sessions.tests.CacheDBSessionWithTimeZoneTests" name="test_session_key_is_read_only" time="0.171834"></testcase><testcase classname="django.contrib.sessions.tests.CacheDBSessionWithTimeZoneTests" name="test_setdefault" time="0.000177"></testcase><testcase classname="django.contrib.sessions.tests.CacheDBSessionWithTimeZoneTests" name="test_store" time="0.000474"></testcase><testcase classname="django.contrib.sessions.tests.CacheDBSessionWithTimeZoneTests" name="test_update" time="0.000195"></testcase><testcase classname="django.contrib.sessions.tests.CacheDBSessionWithTimeZoneTests" name="test_values" time="0.000570"></testcase></testsuite><testsuite name="django.contrib.sessions.tests.CookieSessionTests"><testcase classname="django.contrib.sessions.tests.CookieSessionTests" name="test_actual_expiry" time="0.003939"></testcase><testcase classname="django.contrib.sessions.tests.CookieSessionTests" name="test_clear" time="0.000522"></testcase><testcase classname="django.contrib.sessions.tests.CookieSessionTests" name="test_custom_expiry_datetime" time="0.000609"></testcase><testcase classname="django.contrib.sessions.tests.CookieSessionTests" name="test_custom_expiry_reset" time="0.000574"></testcase><testcase classname="django.contrib.sessions.tests.CookieSessionTests" name="test_custom_expiry_seconds" time="0.000596"></testcase><testcase classname="django.contrib.sessions.tests.CookieSessionTests" name="test_custom_expiry_timedelta" time="0.000625"></testcase><testcase classname="django.contrib.sessions.tests.CookieSessionTests" name="test_cycle" time="0.000346"></testcase><testcase classname="django.contrib.sessions.tests.CookieSessionTests" name="test_decode" time="0.001054"></testcase><testcase classname="django.contrib.sessions.tests.CookieSessionTests" name="test_decode_failure_logged_to_security" time="0.000886"></testcase><testcase classname="django.contrib.sessions.tests.CookieSessionTests" name="test_default_expiry" time="0.000617"></testcase><testcase classname="django.contrib.sessions.tests.CookieSessionTests" name="test_delete" time="0.001109"></testcase><testcase classname="django.contrib.sessions.tests.CookieSessionTests" name="test_flush" time="0.001118"></testcase><testcase classname="django.contrib.sessions.tests.CookieSessionTests" name="test_get_empty" time="0.000418"></testcase><testcase classname="django.contrib.sessions.tests.CookieSessionTests" name="test_get_expire_at_browser_close" time="0.001329"></testcase><testcase classname="django.contrib.sessions.tests.CookieSessionTests" name="test_has_key" time="0.000452"></testcase><testcase classname="django.contrib.sessions.tests.CookieSessionTests" name="test_invalid_key" time="0.001738"></testcase><testcase classname="django.contrib.sessions.tests.CookieSessionTests" name="test_iteritems" time="0.000521"></testcase><testcase classname="django.contrib.sessions.tests.CookieSessionTests" name="test_iterkeys" time="0.000510"></testcase><testcase classname="django.contrib.sessions.tests.CookieSessionTests" name="test_itervalues" time="0.000549"></testcase><testcase classname="django.contrib.sessions.tests.CookieSessionTests" name="test_new_session" time="0.000358"></testcase><testcase classname="django.contrib.sessions.tests.CookieSessionTests" name="test_pop" time="0.000482"></testcase><testcase classname="django.contrib.sessions.tests.CookieSessionTests" name="test_pop_default" time="0.000466"></testcase><testcase classname="django.contrib.sessions.tests.CookieSessionTests" name="test_save" time="0.000363"></testcase><testcase classname="django.contrib.sessions.tests.CookieSessionTests" name="test_session_key_is_read_only" time="0.001393"></testcase><testcase classname="django.contrib.sessions.tests.CookieSessionTests" name="test_setdefault" time="0.000457"></testcase><testcase classname="django.contrib.sessions.tests.CookieSessionTests" name="test_store" time="0.000469"></testcase><testcase classname="django.contrib.sessions.tests.CookieSessionTests" name="test_update" time="0.000460"></testcase><testcase classname="django.contrib.sessions.tests.CookieSessionTests" name="test_values" time="0.000514"></testcase></testsuite><testsuite name="django.contrib.sessions.tests.DatabaseSessionTests"><testcase classname="django.contrib.sessions.tests.DatabaseSessionTests" name="test_actual_expiry" time="1.270241"></testcase><testcase classname="django.contrib.sessions.tests.DatabaseSessionTests" name="test_clear" time="0.000549"></testcase><testcase classname="django.contrib.sessions.tests.DatabaseSessionTests" name="test_clearsessions_command" time="1.460323"></testcase><testcase classname="django.contrib.sessions.tests.DatabaseSessionTests" name="test_custom_expiry_datetime" time="0.000633"></testcase><testcase classname="django.contrib.sessions.tests.DatabaseSessionTests" name="test_custom_expiry_reset" time="0.000606"></testcase><testcase classname="django.contrib.sessions.tests.DatabaseSessionTests" name="test_custom_expiry_seconds" time="0.000586"></testcase><testcase classname="django.contrib.sessions.tests.DatabaseSessionTests" name="test_custom_expiry_timedelta" time="0.000668"></testcase><testcase classname="django.contrib.sessions.tests.DatabaseSessionTests" name="test_cycle" time="1.181835"></testcase><testcase classname="django.contrib.sessions.tests.DatabaseSessionTests" name="test_decode" time="0.001100"></testcase><testcase classname="django.contrib.sessions.tests.DatabaseSessionTests" name="test_decode_failure_logged_to_security" time="0.000974"></testcase><testcase classname="django.contrib.sessions.tests.DatabaseSessionTests" name="test_default_expiry" time="0.000650"></testcase><testcase classname="django.contrib.sessions.tests.DatabaseSessionTests" name="test_delete" time="1.266501"></testcase><testcase classname="django.contrib.sessions.tests.DatabaseSessionTests" name="test_flush" time="1.265981"></testcase><testcase classname="django.contrib.sessions.tests.DatabaseSessionTests" name="test_get_empty" time="0.000446"></testcase><testcase classname="django.contrib.sessions.tests.DatabaseSessionTests" name="test_get_expire_at_browser_close" time="0.001387"></testcase><testcase classname="django.contrib.sessions.tests.DatabaseSessionTests" name="test_has_key" time="0.000454"></testcase><testcase classname="django.contrib.sessions.tests.DatabaseSessionTests" name="test_invalid_key" time="1.205112"></testcase><testcase classname="django.contrib.sessions.tests.DatabaseSessionTests" name="test_iteritems" time="0.000536"></testcase><testcase classname="django.contrib.sessions.tests.DatabaseSessionTests" name="test_iterkeys" time="0.000536"></testcase><testcase classname="django.contrib.sessions.tests.DatabaseSessionTests" name="test_itervalues" time="0.000509"></testcase><testcase classname="django.contrib.sessions.tests.DatabaseSessionTests" name="test_new_session" time="0.000394"></testcase><testcase classname="django.contrib.sessions.tests.DatabaseSessionTests" name="test_pop" time="0.000488"></testcase><testcase classname="django.contrib.sessions.tests.DatabaseSessionTests" name="test_pop_default" time="0.000453"></testcase><testcase classname="django.contrib.sessions.tests.DatabaseSessionTests" name="test_save" time="1.176075"></testcase><testcase classname="django.contrib.sessions.tests.DatabaseSessionTests" name="test_session_get_decoded" time="0.763915"></testcase><testcase classname="django.contrib.sessions.tests.DatabaseSessionTests" name="test_session_key_is_read_only" time="0.170292"></testcase><testcase classname="django.contrib.sessions.tests.DatabaseSessionTests" name="test_sessionmanager_save" time="0.930244"></testcase><testcase classname="django.contrib.sessions.tests.DatabaseSessionTests" name="test_setdefault" time="0.000491"></testcase><testcase classname="django.contrib.sessions.tests.DatabaseSessionTests" name="test_store" time="0.000471"></testcase><testcase classname="django.contrib.sessions.tests.DatabaseSessionTests" name="test_update" time="0.000447"></testcase><testcase classname="django.contrib.sessions.tests.DatabaseSessionTests" name="test_values" time="0.000480"></testcase></testsuite><testsuite name="django.contrib.sessions.tests.DatabaseSessionWithTimeZoneTests"><testcase classname="django.contrib.sessions.tests.DatabaseSessionWithTimeZoneTests" name="test_actual_expiry" time="1.268138"></testcase><testcase classname="django.contrib.sessions.tests.DatabaseSessionWithTimeZoneTests" name="test_clear" time="0.000577"></testcase><testcase classname="django.contrib.sessions.tests.DatabaseSessionWithTimeZoneTests" name="test_clearsessions_command" time="1.444705"></testcase><testcase classname="django.contrib.sessions.tests.DatabaseSessionWithTimeZoneTests" name="test_custom_expiry_datetime" time="0.000609"></testcase><testcase classname="django.contrib.sessions.tests.DatabaseSessionWithTimeZoneTests" name="test_custom_expiry_reset" time="0.000590"></testcase><testcase classname="django.contrib.sessions.tests.DatabaseSessionWithTimeZoneTests" name="test_custom_expiry_seconds" time="0.000598"></testcase><testcase classname="django.contrib.sessions.tests.DatabaseSessionWithTimeZoneTests" name="test_custom_expiry_timedelta" time="0.000687"></testcase><testcase classname="django.contrib.sessions.tests.DatabaseSessionWithTimeZoneTests" name="test_cycle" time="1.167866"></testcase><testcase classname="django.contrib.sessions.tests.DatabaseSessionWithTimeZoneTests" name="test_decode" time="0.001066"></testcase><testcase classname="django.contrib.sessions.tests.DatabaseSessionWithTimeZoneTests" name="test_decode_failure_logged_to_security" time="0.000916"></testcase><testcase classname="django.contrib.sessions.tests.DatabaseSessionWithTimeZoneTests" name="test_default_expiry" time="0.000746"></testcase><testcase classname="django.contrib.sessions.tests.DatabaseSessionWithTimeZoneTests" name="test_delete" time="1.264781"></testcase><testcase classname="django.contrib.sessions.tests.DatabaseSessionWithTimeZoneTests" name="test_flush" time="1.273257"></testcase><testcase classname="django.contrib.sessions.tests.DatabaseSessionWithTimeZoneTests" name="test_get_empty" time="0.000454"></testcase><testcase classname="django.contrib.sessions.tests.DatabaseSessionWithTimeZoneTests" name="test_get_expire_at_browser_close" time="0.001370"></testcase><testcase classname="django.contrib.sessions.tests.DatabaseSessionWithTimeZoneTests" name="test_has_key" time="0.000466"></testcase><testcase classname="django.contrib.sessions.tests.DatabaseSessionWithTimeZoneTests" name="test_invalid_key" time="1.179366"></testcase><testcase classname="django.contrib.sessions.tests.DatabaseSessionWithTimeZoneTests" name="test_iteritems" time="0.000536"></testcase><testcase classname="django.contrib.sessions.tests.DatabaseSessionWithTimeZoneTests" name="test_iterkeys" time="0.000549"></testcase><testcase classname="django.contrib.sessions.tests.DatabaseSessionWithTimeZoneTests" name="test_itervalues" time="0.000537"></testcase><testcase classname="django.contrib.sessions.tests.DatabaseSessionWithTimeZoneTests" name="test_new_session" time="0.000404"></testcase><testcase classname="django.contrib.sessions.tests.DatabaseSessionWithTimeZoneTests" name="test_pop" time="0.000516"></testcase><testcase classname="django.contrib.sessions.tests.DatabaseSessionWithTimeZoneTests" name="test_pop_default" time="0.000465"></testcase><testcase classname="django.contrib.sessions.tests.DatabaseSessionWithTimeZoneTests" name="test_save" time="1.184347"></testcase><testcase classname="django.contrib.sessions.tests.DatabaseSessionWithTimeZoneTests" name="test_session_get_decoded" time="0.759314"></testcase><testcase classname="django.contrib.sessions.tests.DatabaseSessionWithTimeZoneTests" name="test_session_key_is_read_only" time="0.173666"></testcase><testcase classname="django.contrib.sessions.tests.DatabaseSessionWithTimeZoneTests" name="test_sessionmanager_save" time="0.940896"></testcase><testcase classname="django.contrib.sessions.tests.DatabaseSessionWithTimeZoneTests" name="test_setdefault" time="0.000519"></testcase><testcase classname="django.contrib.sessions.tests.DatabaseSessionWithTimeZoneTests" name="test_store" time="0.000464"></testcase><testcase classname="django.contrib.sessions.tests.DatabaseSessionWithTimeZoneTests" name="test_update" time="0.000479"></testcase><testcase classname="django.contrib.sessions.tests.DatabaseSessionWithTimeZoneTests" name="test_values" time="0.000611"></testcase></testsuite><testsuite name="website.tests.CommentEmailIncorrectFormat"><testcase classname="website.tests.CommentEmailIncorrectFormat" name="test_unicode" time="0.003879"><error message="&lt;class 'django.contrib.gis.db.models.fields.MultiPointField'&gt; is not supported by mommy.">Traceback (most recent call last):
  File "/home/derya/Repo/haunted-map/website/tests.py", line 9, in test_unicode
    haunted_location = mommy.make(HauntedLocation)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/model_mommy/mommy.py", line 75, in make
    return mommy.make(**attrs)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/model_mommy/mommy.py", line 241, in make
    return self._make(commit=True, **attrs)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/model_mommy/mommy.py", line 282, in _make
    model_attrs[field.name] = self.generate_value(field)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/model_mommy/mommy.py", line 350, in generate_value
    raise TypeError('%s is not supported by mommy.' % field.__class__)
TypeError: &lt;class 'django.contrib.gis.db.models.fields.MultiPointField'&gt; is not supported by mommy.
</error></testcase></testsuite><testsuite name="django_facebook.tests.AuthBackend"><testcase classname="django_facebook.tests.AuthBackend" name="test_auth_backend" time="3.893397"></testcase></testsuite><testsuite name="django_facebook.tests.BaseDecoratorTest"><testcase classname="django_facebook.tests.BaseDecoratorTest" name="test_naming" time="0.178683"></testcase><testcase classname="django_facebook.tests.BaseDecoratorTest" name="test_wrapping" time="0.174990"></testcase></testsuite><testsuite name="django_facebook.tests.ConnectViewTest"><testcase classname="django_facebook.tests.ConnectViewTest" name="test_connect" time="0.997004"><error message="Reverse for 'facebook_image_upload' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []">Traceback (most recent call last):
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django_facebook/tests.py", line 270, in test_connect
    response = self.client.post(url, post_data, follow=True)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/test/client.py", line 485, in post
    response = self._handle_redirects(response, **extra)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/test/client.py", line 617, in _handle_redirects
    response = self.get(url.path, QueryDict(url.query), follow=False, **extra)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/test/client.py", line 473, in get
    response = super(Client, self).get(path, data=data, **extra)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/test/client.py", line 280, in get
    return self.request(**r)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/test/client.py", line 444, in request
    six.reraise(*exc_info)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django_facebook/views.py", line 138, in example
    return render_to_response('django_facebook/example.html', context)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/shortcuts/__init__.py", line 29, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/template/loader.py", line 164, in render_to_string
    return t.render(Context(dictionary))
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/test/utils.py", line 85, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 447, in render
    six.reraise(*exc_info)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 433, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=context.current_app)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 509, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 429, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'facebook_image_upload' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
</error></testcase><testcase classname="django_facebook.tests.ConnectViewTest" name="test_connect_redirect" time="0.275416"><failure message="'https://www.facebook.com/dialog/oauth?scope=email%2Cuser_about_me%2Cuser_birthday%2Cuser_website&amp;redirect_uri=http%3A%2F%2Ftestserver%2Ffacebook%2Fconnect%2F%3Fattempt%3D1&amp;client_id=275585332592670' != 'https://www.facebook.com/dialog/oauth?scope=email%2Cuser_about_me%2Cuser_birthday%2Cuser_website&amp;redirect_uri=http%3A%2F%2Ftestserver%2Ffacebook%2Fconnect%2F%3Fattempt%3D1&amp;client_id=215464901804004'">Traceback (most recent call last):
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django_facebook/tests.py", line 208, in test_connect_redirect
    self.assertEqual(redirect_url, oauth_url)
AssertionError: 'https://www.facebook.com/dialog/oauth?scope=email%2Cuser_about_me%2Cuser_birthday%2Cuser_website&amp;redirect_uri=http%3A%2F%2Ftestserver%2Ffacebook%2Fconnect%2F%3Fattempt%3D1&amp;client_id=275585332592670' != 'https://www.facebook.com/dialog/oauth?scope=email%2Cuser_about_me%2Cuser_birthday%2Cuser_website&amp;redirect_uri=http%3A%2F%2Ftestserver%2Ffacebook%2Fconnect%2F%3Fattempt%3D1&amp;client_id=215464901804004'
</failure></testcase><testcase classname="django_facebook.tests.ConnectViewTest" name="test_connect_redirect_authenticated" time="2.866949"><error message="value too long for type character varying(1)&#10;">Traceback (most recent call last):
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django_facebook/tests.py", line 217, in test_connect_redirect_authenticated
    response = self.client.get(accepted_url, follow=True)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/test/client.py", line 473, in get
    response = super(Client, self).get(path, data=data, **extra)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/test/client.py", line 280, in get
    return self.request(**r)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/test/client.py", line 444, in request
    six.reraise(*exc_info)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django_facebook/decorators.py", line 99, in wrapped_view
    response = self.authenticate(self.fn, request, *args, **kwargs)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django_facebook/decorators.py", line 180, in authenticate
    fn, request, graph=graph, *args, **kwargs)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django_facebook/decorators.py", line 138, in execute_view
    result = view_func(*args, **kwargs)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django_facebook/views.py", line 40, in connect
    response = _connect(request, graph)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django_facebook/views.py", line 81, in _connect
    request, connect_facebook=connect_facebook)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django_facebook/connect.py", line 89, in connect_user
    remove_old_connections=force_registration)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django_facebook/connect.py", line 254, in _register_user
    new_user = _update_user(new_user, facebook)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django_facebook/connect.py", line 360, in _update_user
    profile.save()
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/models/base.py", line 545, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/models/base.py", line 573, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/models/base.py", line 635, in _save_table
    forced_update)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/models/base.py", line 679, in _do_update
    return filtered._update(values) &gt; 0
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/models/query.py", line 507, in _update
    return query.get_compiler(self.db).execute_sql(None)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 975, in execute_sql
    cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 781, in execute_sql
    cursor.execute(sql, params)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
DataError: value too long for type character varying(1)

</error></testcase><testcase classname="django_facebook.tests.ConnectViewTest" name="test_connect_redirect_default" time="2.630052"><error message="value too long for type character varying(1)&#10;">Traceback (most recent call last):
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django_facebook/tests.py", line 232, in test_connect_redirect_default
    response = self.client.get(accepted_url, follow=True)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/test/client.py", line 473, in get
    response = super(Client, self).get(path, data=data, **extra)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/test/client.py", line 280, in get
    return self.request(**r)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/test/client.py", line 444, in request
    six.reraise(*exc_info)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django_facebook/decorators.py", line 99, in wrapped_view
    response = self.authenticate(self.fn, request, *args, **kwargs)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django_facebook/decorators.py", line 180, in authenticate
    fn, request, graph=graph, *args, **kwargs)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django_facebook/decorators.py", line 138, in execute_view
    result = view_func(*args, **kwargs)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django_facebook/views.py", line 40, in connect
    response = _connect(request, graph)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django_facebook/views.py", line 81, in _connect
    request, connect_facebook=connect_facebook)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django_facebook/connect.py", line 89, in connect_user
    remove_old_connections=force_registration)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django_facebook/connect.py", line 254, in _register_user
    new_user = _update_user(new_user, facebook)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django_facebook/connect.py", line 360, in _update_user
    profile.save()
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/models/base.py", line 545, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/models/base.py", line 573, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/models/base.py", line 635, in _save_table
    forced_update)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/models/base.py", line 679, in _do_update
    return filtered._update(values) &gt; 0
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/models/query.py", line 507, in _update
    return query.get_compiler(self.db).execute_sql(None)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 975, in execute_sql
    cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 781, in execute_sql
    cursor.execute(sql, params)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
DataError: value too long for type character varying(1)

</error></testcase><testcase classname="django_facebook.tests.ConnectViewTest" name="test_connect_redirect_not_authenticated" time="0.283944"><error message="Reverse for 'facebook_image_upload' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []">Traceback (most recent call last):
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django_facebook/tests.py", line 242, in test_connect_redirect_not_authenticated
    response = self.client.get(accepted_url, follow=True)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/test/client.py", line 475, in get
    response = self._handle_redirects(response, **extra)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/test/client.py", line 617, in _handle_redirects
    response = self.get(url.path, QueryDict(url.query), follow=False, **extra)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/test/client.py", line 473, in get
    response = super(Client, self).get(path, data=data, **extra)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/test/client.py", line 280, in get
    return self.request(**r)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/test/client.py", line 444, in request
    six.reraise(*exc_info)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django_facebook/views.py", line 138, in example
    return render_to_response('django_facebook/example.html', context)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/shortcuts/__init__.py", line 29, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/template/loader.py", line 164, in render_to_string
    return t.render(Context(dictionary))
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/test/utils.py", line 85, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 447, in render
    six.reraise(*exc_info)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 433, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=context.current_app)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 509, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 429, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'facebook_image_upload' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
</error></testcase><testcase classname="django_facebook.tests.ConnectViewTest" name="test_slow_connect" time="0.836603"><error message="Reverse for 'facebook_image_upload' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []">Traceback (most recent call last):
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django_facebook/tests.py", line 342, in test_slow_connect
    response = self.client.post(url, post_data, follow=True)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/test/client.py", line 485, in post
    response = self._handle_redirects(response, **extra)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/test/client.py", line 617, in _handle_redirects
    response = self.get(url.path, QueryDict(url.query), follow=False, **extra)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/test/client.py", line 473, in get
    response = super(Client, self).get(path, data=data, **extra)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/test/client.py", line 280, in get
    return self.request(**r)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/test/client.py", line 444, in request
    six.reraise(*exc_info)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django_facebook/views.py", line 138, in example
    return render_to_response('django_facebook/example.html', context)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/shortcuts/__init__.py", line 29, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/template/loader.py", line 164, in render_to_string
    return t.render(Context(dictionary))
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/test/utils.py", line 85, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 447, in render
    six.reraise(*exc_info)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 433, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=context.current_app)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 509, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 429, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'facebook_image_upload' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
</error></testcase></testsuite><testsuite name="django_facebook.tests.DecoratorTest"><testcase classname="django_facebook.tests.DecoratorTest" name="test_decorator_authenticated" time="0.277836"><error message="Reverse for 'facebook_decorator_example' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []">Traceback (most recent call last):
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django_facebook/tests.py", line 87, in setUp
    self.url = reverse('facebook_decorator_example')
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 509, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 429, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'facebook_decorator_example' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
</error></testcase><testcase classname="django_facebook.tests.DecoratorTest" name="test_decorator_denied" time="0.269063"><error message="Reverse for 'facebook_decorator_example' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []">Traceback (most recent call last):
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django_facebook/tests.py", line 87, in setUp
    self.url = reverse('facebook_decorator_example')
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 509, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 429, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'facebook_decorator_example' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
</error></testcase><testcase classname="django_facebook.tests.DecoratorTest" name="test_decorator_not_authenticated" time="0.263349"><error message="Reverse for 'facebook_decorator_example' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []">Traceback (most recent call last):
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django_facebook/tests.py", line 87, in setUp
    self.url = reverse('facebook_decorator_example')
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 509, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 429, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'facebook_decorator_example' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
</error></testcase><testcase classname="django_facebook.tests.DecoratorTest" name="test_naming" time="0.277455"><error message="Reverse for 'facebook_decorator_example' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []">Traceback (most recent call last):
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django_facebook/tests.py", line 87, in setUp
    self.url = reverse('facebook_decorator_example')
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 509, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 429, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'facebook_decorator_example' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
</error></testcase><testcase classname="django_facebook.tests.DecoratorTest" name="test_wrapping" time="0.261617"><error message="Reverse for 'facebook_decorator_example' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []">Traceback (most recent call last):
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django_facebook/tests.py", line 87, in setUp
    self.url = reverse('facebook_decorator_example')
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 509, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 429, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'facebook_decorator_example' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
</error></testcase></testsuite><testsuite name="django_facebook.tests.ErrorMappingTest"><testcase classname="django_facebook.tests.ErrorMappingTest" name="test_mapping" time="0.261354"></testcase></testsuite><testsuite name="django_facebook.tests.ExtendTokenTest"><testcase classname="django_facebook.tests.ExtendTokenTest" name="test_extend_token" time="0.000286"></testcase></testsuite><testsuite name="django_facebook.tests.FacebookCanvasMiddlewareTest"><testcase classname="django_facebook.tests.FacebookCanvasMiddlewareTest" name="test_auth_user" time="0.292580"></testcase><testcase classname="django_facebook.tests.FacebookCanvasMiddlewareTest" name="test_non_auth_user" time="0.268247"></testcase><testcase classname="django_facebook.tests.FacebookCanvasMiddlewareTest" name="test_referer" time="0.280499"></testcase><testcase classname="django_facebook.tests.FacebookCanvasMiddlewareTest" name="test_user_denied" time="0.263803"></testcase></testsuite><testsuite name="django_facebook.tests.GraphAccessTest"><testcase classname="django_facebook.tests.GraphAccessTest" name="test_get_persistent" time="0.445081"></testcase></testsuite><testsuite name="django_facebook.tests.LazyDecoratorTest"><testcase classname="django_facebook.tests.LazyDecoratorTest" name="test_decorator_authenticated" time="0.260801"><error message="Reverse for 'facebook_decorator_example' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []">Traceback (most recent call last):
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django_facebook/tests.py", line 160, in setUp
    DecoratorTest.setUp(self)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django_facebook/tests.py", line 87, in setUp
    self.url = reverse('facebook_decorator_example')
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 509, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 429, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'facebook_decorator_example' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
</error></testcase><testcase classname="django_facebook.tests.LazyDecoratorTest" name="test_decorator_denied" time="0.263573"><error message="Reverse for 'facebook_decorator_example' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []">Traceback (most recent call last):
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django_facebook/tests.py", line 160, in setUp
    DecoratorTest.setUp(self)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django_facebook/tests.py", line 87, in setUp
    self.url = reverse('facebook_decorator_example')
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 509, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 429, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'facebook_decorator_example' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
</error></testcase><testcase classname="django_facebook.tests.LazyDecoratorTest" name="test_decorator_not_authenticated" time="0.261847"><error message="Reverse for 'facebook_decorator_example' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []">Traceback (most recent call last):
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django_facebook/tests.py", line 160, in setUp
    DecoratorTest.setUp(self)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django_facebook/tests.py", line 87, in setUp
    self.url = reverse('facebook_decorator_example')
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 509, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 429, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'facebook_decorator_example' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
</error></testcase><testcase classname="django_facebook.tests.LazyDecoratorTest" name="test_naming" time="0.261608"><error message="Reverse for 'facebook_decorator_example' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []">Traceback (most recent call last):
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django_facebook/tests.py", line 160, in setUp
    DecoratorTest.setUp(self)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django_facebook/tests.py", line 87, in setUp
    self.url = reverse('facebook_decorator_example')
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 509, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 429, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'facebook_decorator_example' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
</error></testcase><testcase classname="django_facebook.tests.LazyDecoratorTest" name="test_wrapping" time="0.255973"><error message="Reverse for 'facebook_decorator_example' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []">Traceback (most recent call last):
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django_facebook/tests.py", line 160, in setUp
    DecoratorTest.setUp(self)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django_facebook/tests.py", line 87, in setUp
    self.url = reverse('facebook_decorator_example')
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 509, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 429, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'facebook_decorator_example' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
</error></testcase></testsuite><testsuite name="django_facebook.tests.OAuthUrlTest"><testcase classname="django_facebook.tests.OAuthUrlTest" name="test_url" time="0.263598"></testcase></testsuite><testsuite name="django_facebook.tests.OpenGraphShareTest"><testcase classname="django_facebook.tests.OpenGraphShareTest" name="test_follow_og_share" time="1.570625"></testcase><testcase classname="django_facebook.tests.OpenGraphShareTest" name="test_follow_og_share_error" time="2.646878"></testcase></testsuite><testsuite name="django_facebook.tests.ScopedDecoratorTest"><testcase classname="django_facebook.tests.ScopedDecoratorTest" name="test_decorator_authenticated" time="0.276816"><error message="Reverse for 'facebook_decorator_example' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []">Traceback (most recent call last):
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django_facebook/tests.py", line 131, in setUp
    DecoratorTest.setUp(self)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django_facebook/tests.py", line 87, in setUp
    self.url = reverse('facebook_decorator_example')
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 509, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 429, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'facebook_decorator_example' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
</error></testcase><testcase classname="django_facebook.tests.ScopedDecoratorTest" name="test_decorator_denied" time="0.261826"><error message="Reverse for 'facebook_decorator_example' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []">Traceback (most recent call last):
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django_facebook/tests.py", line 131, in setUp
    DecoratorTest.setUp(self)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django_facebook/tests.py", line 87, in setUp
    self.url = reverse('facebook_decorator_example')
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 509, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 429, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'facebook_decorator_example' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
</error></testcase><testcase classname="django_facebook.tests.ScopedDecoratorTest" name="test_decorator_not_authenticated" time="0.261052"><error message="Reverse for 'facebook_decorator_example' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []">Traceback (most recent call last):
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django_facebook/tests.py", line 131, in setUp
    DecoratorTest.setUp(self)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django_facebook/tests.py", line 87, in setUp
    self.url = reverse('facebook_decorator_example')
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 509, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 429, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'facebook_decorator_example' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
</error></testcase><testcase classname="django_facebook.tests.ScopedDecoratorTest" name="test_naming" time="0.261606"><error message="Reverse for 'facebook_decorator_example' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []">Traceback (most recent call last):
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django_facebook/tests.py", line 131, in setUp
    DecoratorTest.setUp(self)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django_facebook/tests.py", line 87, in setUp
    self.url = reverse('facebook_decorator_example')
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 509, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 429, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'facebook_decorator_example' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
</error></testcase><testcase classname="django_facebook.tests.ScopedDecoratorTest" name="test_type_error" time="0.261117"><error message="Reverse for 'facebook_decorator_example' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []">Traceback (most recent call last):
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django_facebook/tests.py", line 131, in setUp
    DecoratorTest.setUp(self)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django_facebook/tests.py", line 87, in setUp
    self.url = reverse('facebook_decorator_example')
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 509, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 429, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'facebook_decorator_example' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
</error></testcase><testcase classname="django_facebook.tests.ScopedDecoratorTest" name="test_wrapping" time="0.263081"><error message="Reverse for 'facebook_decorator_example' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []">Traceback (most recent call last):
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django_facebook/tests.py", line 131, in setUp
    DecoratorTest.setUp(self)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django_facebook/tests.py", line 87, in setUp
    self.url = reverse('facebook_decorator_example')
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 509, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 429, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'facebook_decorator_example' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
</error></testcase></testsuite><testsuite name="django_facebook.tests.SignalTest"><testcase classname="django_facebook.tests.SignalTest" name="test_user_registered_signal" time="2.337273"><error message="value too long for type character varying(1)&#10;">Traceback (most recent call last):
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django_facebook/tests.py", line 805, in test_user_registered_signal
    user = _register_user(self.request, facebook)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django_facebook/connect.py", line 254, in _register_user
    new_user = _update_user(new_user, facebook)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django_facebook/connect.py", line 360, in _update_user
    profile.save()
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/models/base.py", line 545, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/models/base.py", line 573, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/models/base.py", line 635, in _save_table
    forced_update)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/models/base.py", line 679, in _do_update
    return filtered._update(values) &gt; 0
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/models/query.py", line 507, in _update
    return query.get_compiler(self.db).execute_sql(None)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 975, in execute_sql
    cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 781, in execute_sql
    cursor.execute(sql, params)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
DataError: value too long for type character varying(1)

</error></testcase></testsuite><testsuite name="django_facebook.tests.SimpleRegisterViewTest"><testcase classname="django_facebook.tests.SimpleRegisterViewTest" name="test_registration" time="1.834284"></testcase></testsuite><testsuite name="django_facebook.tests.TestUserTest"><testcase classname="django_facebook.tests.TestUserTest" name="test_create_test_user" time="0.000307"></testcase></testsuite><testsuite name="django_facebook.tests.UserConnectTest"><testcase classname="django_facebook.tests.UserConnectTest" name="test_current_user" time="1.653937"><error message="value too long for type character varying(1)&#10;">Traceback (most recent call last):
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django_facebook/tests.py", line 626, in test_current_user
    action, user = connect_user(self.request, facebook_graph=facebook)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django_facebook/connect.py", line 82, in connect_user
    user = _login_user(request, converter, auth_user, update=update)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django_facebook/connect.py", line 116, in _login_user
    _connect_user(request, facebook)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django_facebook/connect.py", line 140, in _connect_user
    user = _update_user(request.user, facebook, overwrite=overwrite)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django_facebook/connect.py", line 360, in _update_user
    profile.save()
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/models/base.py", line 545, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/models/base.py", line 573, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/models/base.py", line 635, in _save_table
    forced_update)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/models/base.py", line 679, in _do_update
    return filtered._update(values) &gt; 0
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/models/query.py", line 507, in _update
    return query.get_compiler(self.db).execute_sql(None)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 975, in execute_sql
    cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 781, in execute_sql
    cursor.execute(sql, params)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
DataError: value too long for type character varying(1)

</error></testcase><testcase classname="django_facebook.tests.UserConnectTest" name="test_double_username" time="2.418408"><error message="value too long for type character varying(1)&#10;">Traceback (most recent call last):
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django_facebook/tests.py", line 670, in test_double_username
    action, user = connect_user(self.request, facebook_graph=facebook)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django_facebook/connect.py", line 89, in connect_user
    remove_old_connections=force_registration)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django_facebook/connect.py", line 254, in _register_user
    new_user = _update_user(new_user, facebook)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django_facebook/connect.py", line 360, in _update_user
    profile.save()
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/models/base.py", line 545, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/models/base.py", line 573, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/models/base.py", line 635, in _save_table
    forced_update)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/models/base.py", line 679, in _do_update
    return filtered._update(values) &gt; 0
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/models/query.py", line 507, in _update
    return query.get_compiler(self.db).execute_sql(None)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 975, in execute_sql
    cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 781, in execute_sql
    cursor.execute(sql, params)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
DataError: value too long for type character varying(1)

</error></testcase><testcase classname="django_facebook.tests.UserConnectTest" name="test_fb_update_required" time="1.684607"><error message="value too long for type character varying(1)&#10;">Traceback (most recent call last):
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django_facebook/tests.py", line 639, in test_fb_update_required
    action, user = connect_user(self.request, facebook_graph=facebook)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django_facebook/connect.py", line 82, in connect_user
    user = _login_user(request, converter, auth_user, update=update)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django_facebook/connect.py", line 116, in _login_user
    _connect_user(request, facebook)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django_facebook/connect.py", line 140, in _connect_user
    user = _update_user(request.user, facebook, overwrite=overwrite)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django_facebook/connect.py", line 360, in _update_user
    profile.save()
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/models/base.py", line 545, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/models/base.py", line 573, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/models/base.py", line 635, in _save_table
    forced_update)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/models/base.py", line 679, in _do_update
    return filtered._update(values) &gt; 0
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/models/query.py", line 507, in _update
    return query.get_compiler(self.db).execute_sql(None)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 975, in execute_sql
    cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 781, in execute_sql
    cursor.execute(sql, params)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
DataError: value too long for type character varying(1)

</error></testcase><testcase classname="django_facebook.tests.UserConnectTest" name="test_full_connect" time="2.380981"><error message="value too long for type character varying(1)&#10;">Traceback (most recent call last):
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django_facebook/tests.py", line 570, in test_full_connect
    action, user = connect_user(self.request, facebook_graph=graph)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django_facebook/connect.py", line 89, in connect_user
    remove_old_connections=force_registration)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django_facebook/connect.py", line 254, in _register_user
    new_user = _update_user(new_user, facebook)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django_facebook/connect.py", line 360, in _update_user
    profile.save()
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/models/base.py", line 545, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/models/base.py", line 573, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/models/base.py", line 635, in _save_table
    forced_update)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/models/base.py", line 679, in _do_update
    return filtered._update(values) &gt; 0
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/models/query.py", line 507, in _update
    return query.get_compiler(self.db).execute_sql(None)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 975, in execute_sql
    cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 781, in execute_sql
    cursor.execute(sql, params)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
DataError: value too long for type character varying(1)

</error></testcase><testcase classname="django_facebook.tests.UserConnectTest" name="test_gender" time="0.351585"></testcase><testcase classname="django_facebook.tests.UserConnectTest" name="test_gender_matching" time="2.748352"></testcase><testcase classname="django_facebook.tests.UserConnectTest" name="test_invalid_token" time="0.268328"></testcase><testcase classname="django_facebook.tests.UserConnectTest" name="test_long_username" time="2.454823"><error message="value too long for type character varying(1)&#10;">Traceback (most recent call last):
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django_facebook/tests.py", line 560, in test_long_username
    action, user = connect_user(self.request, facebook_graph=graph)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django_facebook/connect.py", line 89, in connect_user
    remove_old_connections=force_registration)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django_facebook/connect.py", line 254, in _register_user
    new_user = _update_user(new_user, facebook)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django_facebook/connect.py", line 360, in _update_user
    profile.save()
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/models/base.py", line 545, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/models/base.py", line 573, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/models/base.py", line 635, in _save_table
    forced_update)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/models/base.py", line 679, in _do_update
    return filtered._update(values) &gt; 0
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/models/query.py", line 507, in _update
    return query.get_compiler(self.db).execute_sql(None)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 975, in execute_sql
    cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 781, in execute_sql
    cursor.execute(sql, params)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
DataError: value too long for type character varying(1)

</error></testcase><testcase classname="django_facebook.tests.UserConnectTest" name="test_new_user" time="2.854462"></testcase><testcase classname="django_facebook.tests.UserConnectTest" name="test_no_email_registration" time="0.630140"></testcase><testcase classname="django_facebook.tests.UserConnectTest" name="test_parallel_register" time="2.840439"><error message="value too long for type character varying(1)&#10;">Traceback (most recent call last):
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django_facebook/tests.py", line 592, in test_parallel_register
    action, user = connect_user(self.request, facebook_graph=graph)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django_facebook/connect.py", line 89, in connect_user
    remove_old_connections=force_registration)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django_facebook/connect.py", line 254, in _register_user
    new_user = _update_user(new_user, facebook)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django_facebook/connect.py", line 360, in _update_user
    profile.save()
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/models/base.py", line 545, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/models/base.py", line 573, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/models/base.py", line 635, in _save_table
    forced_update)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/models/base.py", line 679, in _do_update
    return filtered._update(values) &gt; 0
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/models/query.py", line 507, in _update
    return query.get_compiler(self.db).execute_sql(None)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 975, in execute_sql
    cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 781, in execute_sql
    cursor.execute(sql, params)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
DataError: value too long for type character varying(1)

</error></testcase><testcase classname="django_facebook.tests.UserConnectTest" name="test_persistent_graph" time="2.860235"><error message="value too long for type character varying(1)&#10;">Traceback (most recent call last):
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django_facebook/tests.py", line 497, in test_persistent_graph
    action, user = connect_user(self.request, facebook_graph=graph)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django_facebook/connect.py", line 89, in connect_user
    remove_old_connections=force_registration)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django_facebook/connect.py", line 254, in _register_user
    new_user = _update_user(new_user, facebook)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django_facebook/connect.py", line 360, in _update_user
    profile.save()
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/models/base.py", line 545, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/models/base.py", line 573, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/models/base.py", line 635, in _save_table
    forced_update)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/models/base.py", line 679, in _do_update
    return filtered._update(values) &gt; 0
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/models/query.py", line 507, in _update
    return query.get_compiler(self.db).execute_sql(None)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 975, in execute_sql
    cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 781, in execute_sql
    cursor.execute(sql, params)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
DataError: value too long for type character varying(1)

</error></testcase><testcase classname="django_facebook.tests.UserConnectTest" name="test_registration_form" time="0.282080"><error message="'Settings' object has no attribute 'MODE'">Traceback (most recent call last):
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django_facebook/tests.py", line 684, in test_registration_form
    if settings.MODE == 'userena':
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/conf/__init__.py", line 55, in __getattr__
    return getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'MODE'
</error></testcase><testcase classname="django_facebook.tests.UserConnectTest" name="test_short_username" time="2.386087"><error message="value too long for type character varying(1)&#10;">Traceback (most recent call last):
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django_facebook/tests.py", line 654, in test_short_username
    action, user = connect_user(self.request, facebook_graph=facebook)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django_facebook/connect.py", line 89, in connect_user
    remove_old_connections=force_registration)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django_facebook/connect.py", line 254, in _register_user
    new_user = _update_user(new_user, facebook)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django_facebook/connect.py", line 360, in _update_user
    profile.save()
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/models/base.py", line 545, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/models/base.py", line 573, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/models/base.py", line 635, in _save_table
    forced_update)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/models/base.py", line 679, in _do_update
    return filtered._update(values) &gt; 0
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/models/query.py", line 507, in _update
    return query.get_compiler(self.db).execute_sql(None)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 975, in execute_sql
    cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 781, in execute_sql
    cursor.execute(sql, params)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/derya/virt_env/haunted-map-env/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
DataError: value too long for type character varying(1)

</error></testcase><testcase classname="django_facebook.tests.UserConnectTest" name="test_update_access_token" time="4.145582"></testcase><testcase classname="django_facebook.tests.UserConnectTest" name="test_utf8" time="2.739073"></testcase></testsuite><testsuite name="django_jenkins.tests.SanityCheckTest"><testcase classname="django_jenkins.tests.SanityCheckTest" name="test_is_ok" time="0.000297"></testcase></testsuite><testsuite name="django.contrib.sessions.tests.CacheSessionTests"><testcase classname="django.contrib.sessions.tests.CacheSessionTests" name="test_actual_expiry" time="0.007222"></testcase><testcase classname="django.contrib.sessions.tests.CacheSessionTests" name="test_clear" time="0.000816"></testcase><testcase classname="django.contrib.sessions.tests.CacheSessionTests" name="test_custom_expiry_datetime" time="0.000803"></testcase><testcase classname="django.contrib.sessions.tests.CacheSessionTests" name="test_custom_expiry_reset" time="0.000769"></testcase><testcase classname="django.contrib.sessions.tests.CacheSessionTests" name="test_custom_expiry_seconds" time="0.000767"></testcase><testcase classname="django.contrib.sessions.tests.CacheSessionTests" name="test_custom_expiry_timedelta" time="0.000835"></testcase><testcase classname="django.contrib.sessions.tests.CacheSessionTests" name="test_cycle" time="0.003531"></testcase><testcase classname="django.contrib.sessions.tests.CacheSessionTests" name="test_decode" time="0.000413"></testcase><testcase classname="django.contrib.sessions.tests.CacheSessionTests" name="test_decode_failure_logged_to_security" time="0.000319"></testcase><testcase classname="django.contrib.sessions.tests.CacheSessionTests" name="test_default_cache" time="0.001308"></testcase><testcase classname="django.contrib.sessions.tests.CacheSessionTests" name="test_default_expiry" time="0.000281"></testcase><testcase classname="django.contrib.sessions.tests.CacheSessionTests" name="test_delete" time="0.001297"></testcase><testcase classname="django.contrib.sessions.tests.CacheSessionTests" name="test_flush" time="0.001185"></testcase><testcase classname="django.contrib.sessions.tests.CacheSessionTests" name="test_get_empty" time="0.000211"></testcase><testcase classname="django.contrib.sessions.tests.CacheSessionTests" name="test_get_expire_at_browser_close" time="0.000424"></testcase><testcase classname="django.contrib.sessions.tests.CacheSessionTests" name="test_has_key" time="0.000197"></testcase><testcase classname="django.contrib.sessions.tests.CacheSessionTests" name="test_invalid_key" time="0.000985"></testcase><testcase classname="django.contrib.sessions.tests.CacheSessionTests" name="test_iteritems" time="0.000223"></testcase><testcase classname="django.contrib.sessions.tests.CacheSessionTests" name="test_iterkeys" time="0.000240"></testcase><testcase classname="django.contrib.sessions.tests.CacheSessionTests" name="test_itervalues" time="0.000240"></testcase><testcase classname="django.contrib.sessions.tests.CacheSessionTests" name="test_load_overlong_key" time="0.001130"></testcase><testcase classname="django.contrib.sessions.tests.CacheSessionTests" name="test_new_session" time="0.000223"></testcase><testcase classname="django.contrib.sessions.tests.CacheSessionTests" name="test_non_default_cache" time="0.048643"></testcase><testcase classname="django.contrib.sessions.tests.CacheSessionTests" name="test_pop" time="0.000809"></testcase><testcase classname="django.contrib.sessions.tests.CacheSessionTests" name="test_pop_default" time="0.000627"></testcase><testcase classname="django.contrib.sessions.tests.CacheSessionTests" name="test_save" time="0.001365"></testcase><testcase classname="django.contrib.sessions.tests.CacheSessionTests" name="test_session_key_is_read_only" time="0.000565"></testcase><testcase classname="django.contrib.sessions.tests.CacheSessionTests" name="test_setdefault" time="0.000255"></testcase><testcase classname="django.contrib.sessions.tests.CacheSessionTests" name="test_store" time="0.000231"></testcase><testcase classname="django.contrib.sessions.tests.CacheSessionTests" name="test_update" time="0.000226"></testcase><testcase classname="django.contrib.sessions.tests.CacheSessionTests" name="test_values" time="0.000247"></testcase></testsuite><testsuite name="django.contrib.sessions.tests.FileSessionTests"><testcase classname="django.contrib.sessions.tests.FileSessionTests" name="test_actual_expiry" time="0.013141"></testcase><testcase classname="django.contrib.sessions.tests.FileSessionTests" name="test_clear" time="0.000537"></testcase><testcase classname="django.contrib.sessions.tests.FileSessionTests" name="test_clearsessions_command" time="0.009406"></testcase><testcase classname="django.contrib.sessions.tests.FileSessionTests" name="test_configuration_check" time="0.000402"></testcase><testcase classname="django.contrib.sessions.tests.FileSessionTests" name="test_custom_expiry_datetime" time="0.000310"></testcase><testcase classname="django.contrib.sessions.tests.FileSessionTests" name="test_custom_expiry_reset" time="0.000257"></testcase><testcase classname="django.contrib.sessions.tests.FileSessionTests" name="test_custom_expiry_seconds" time="0.000299"></testcase><testcase classname="django.contrib.sessions.tests.FileSessionTests" name="test_custom_expiry_timedelta" time="0.000306"></testcase><testcase classname="django.contrib.sessions.tests.FileSessionTests" name="test_cycle" time="0.001575"></testcase><testcase classname="django.contrib.sessions.tests.FileSessionTests" name="test_decode" time="0.000409"></testcase><testcase classname="django.contrib.sessions.tests.FileSessionTests" name="test_decode_failure_logged_to_security" time="0.000355"></testcase><testcase classname="django.contrib.sessions.tests.FileSessionTests" name="test_default_expiry" time="0.000314"></testcase><testcase classname="django.contrib.sessions.tests.FileSessionTests" name="test_delete" time="0.000999"></testcase><testcase classname="django.contrib.sessions.tests.FileSessionTests" name="test_flush" time="0.001562"></testcase><testcase classname="django.contrib.sessions.tests.FileSessionTests" name="test_get_empty" time="0.000229"></testcase><testcase classname="django.contrib.sessions.tests.FileSessionTests" name="test_get_expire_at_browser_close" time="0.000462"></testcase><testcase classname="django.contrib.sessions.tests.FileSessionTests" name="test_has_key" time="0.000261"></testcase><testcase classname="django.contrib.sessions.tests.FileSessionTests" name="test_invalid_key" time="0.001276"></testcase><testcase classname="django.contrib.sessions.tests.FileSessionTests" name="test_invalid_key_backslash" time="0.000266"></testcase><testcase classname="django.contrib.sessions.tests.FileSessionTests" name="test_invalid_key_forwardslash" time="0.000275"></testcase><testcase classname="django.contrib.sessions.tests.FileSessionTests" name="test_iteritems" time="0.000278"></testcase><testcase classname="django.contrib.sessions.tests.FileSessionTests" name="test_iterkeys" time="0.000243"></testcase><testcase classname="django.contrib.sessions.tests.FileSessionTests" name="test_itervalues" time="0.000241"></testcase><testcase classname="django.contrib.sessions.tests.FileSessionTests" name="test_new_session" time="0.000202"></testcase><testcase classname="django.contrib.sessions.tests.FileSessionTests" name="test_pop" time="0.000266"></testcase><testcase classname="django.contrib.sessions.tests.FileSessionTests" name="test_pop_default" time="0.000244"></testcase><testcase classname="django.contrib.sessions.tests.FileSessionTests" name="test_save" time="0.000835"></testcase><testcase classname="django.contrib.sessions.tests.FileSessionTests" name="test_session_key_is_read_only" time="0.000530"></testcase><testcase classname="django.contrib.sessions.tests.FileSessionTests" name="test_setdefault" time="0.000270"></testcase><testcase classname="django.contrib.sessions.tests.FileSessionTests" name="test_store" time="0.000262"></testcase><testcase classname="django.contrib.sessions.tests.FileSessionTests" name="test_update" time="0.000270"></testcase><testcase classname="django.contrib.sessions.tests.FileSessionTests" name="test_values" time="0.000274"></testcase></testsuite><testsuite name="django.contrib.sessions.tests.SessionMiddlewareTests"><testcase classname="django.contrib.sessions.tests.SessionMiddlewareTests" name="test_httponly_session_cookie" time="0.949189"></testcase><testcase classname="django.contrib.sessions.tests.SessionMiddlewareTests" name="test_no_httponly_session_cookie" time="0.449887"></testcase><testcase classname="django.contrib.sessions.tests.SessionMiddlewareTests" name="test_secure_session_cookie" time="0.438227"></testcase><testcase classname="django.contrib.sessions.tests.SessionMiddlewareTests" name="test_session_save_on_500" time="0.433040"></testcase></testsuite></testsuites>